erDiagram
    USUARIO{
        int    CPF PK
        int    telefone
        int(8) RA
        bool   isProf
        string instituicao
        string nome
        string email
        string senha
    }

    EVENTO{
        int    id           PK
        string nome
        string publicoAlvo
        string competencias
        string conteudo
    }

    OCORRENCIA{
        int     idDetelhe   FK,PK
        string  local       FK,PK
        int     cargaHoraria
        date    inicio
        date    fim
    }

    DETALHE{
        int    id               PK
        int    idTipo           PK
        ind    idEvento         FK
        int    CPFresponsavel   FK 
        int    maxParticipantes
        string objetivoEvento
        string modalidade
    }

    APLICADOR{
        int idDetalhes FK,PK
        int CPF        FK,PK
    }

    SALA{
        string id           PK
        string detalhes
        int    capacidade
    }

    TIPO{
        int    id   PK
        string tipo
    }



    APLICADOR }|--|{ USUARIO : sao

    OCORRENCIA ||--|| SALA : tem

    DETALHE }|--|| EVENTO : tem
    DETALHE }|--|{ APLICADOR : tem
    DETALHE ||--|| USUARIO : tem
    DETALHE ||--|| OCORRENCIA : tem
    DETALHE ||--|{ TIPO : tem
